pipeline {
    agent any
    stages {
        stage('Setup') {
            steps {
                sh 'python -m pip install -r requirements.txt'
                sh 'playwright install chromium'
            }
        }
        stage('Run Tests') {
            steps {
                sh 'pytest testcases/ --alluredir=reports/allure-results'
            }
        }
        stage('Generate Report') {
            steps {
                allure includeProperties: false, jdk: '', results: [[path: 'reports/allure-results']]
            }
        }
    }
}