"""
交易接口错误码定义
"""

# 成功
SUCCESS = 0
SUCCESS_MSG = "成功"

# 交易相关错误
TRADE_FAILED = 1001
TRADE_FAILED_MSG = "交易失败"

INSUFFICIENT_FUNDS = 1002
INSUFFICIENT_FUNDS_MSG = "资金不足"

INSUFFICIENT_POSITION = 1003
INSUFFICIENT_POSITION_MSG = "持仓不足"

INVALID_AMOUNT = 1004
INVALID_AMOUNT_MSG = "委托数量无效"

# 系统相关错误
SYSTEM_ERROR = 2001
SYSTEM_ERROR_MSG = "系统错误"

CLIENT_NOT_INITIALIZED = 2002
CLIENT_NOT_INITIALIZED_MSG = "交易客户端未初始化"

# 网络相关错误
NETWORK_ERROR = 3001
NETWORK_ERROR_MSG = "网络错误"

TIMEOUT_ERROR = 3002
TIMEOUT_ERROR_MSG = "请求超时"

# 错误码到错误信息的映射
ERROR_MESSAGES = {
    SUCCESS: SUCCESS_MSG,
    TRADE_FAILED: TRADE_FAILED_MSG,
    INSUFFICIENT_FUNDS: INSUFFICIENT_FUNDS_MSG,
    INSUFFICIENT_POSITION: INSUFFICIENT_POSITION_MSG,
    INVALID_AMOUNT: INVALID_AMOUNT_MSG,
    SYSTEM_ERROR: SYSTEM_ERROR_MSG,
    CLIENT_NOT_INITIALIZED: CLIENT_NOT_INITIALIZED_MSG,
    NETWORK_ERROR: NETWORK_ERROR_MSG,
    TIMEOUT_ERROR: TIMEOUT_ERROR_MSG
}


def get_error_message(error_code):
    """
    根据错误码获取错误信息
    
    Args:
        error_code (int): 错误码
        
    Returns:
        str: 错误信息
    """
    return ERROR_MESSAGES.get(error_code, "未知错误")