# generate_test_case.py
import argparse
from pathlib import Path

import allure
import pytest

from element_scraper import scrape_page_elements
from generate_page_object import generate_page_object


def generate_test_case(class_name):
    """生成自动化测试用例"""
    # 动态导入生成的PO类
    import importlib
    module = importlib.import_module(class_name)
    po_class = getattr(module, class_name)

    test_code = f'''# test_{class_name.lower()}.py
import allure
import pytest
from {class_name} import {class_name}
from playwright.sync_api import Page  # 确保导入Page对象

@pytest.fixture
def page(browser):
    return browser.new_page()

@pytest.fixture
def {class_name.lower()}(page: Page):
    return {class_name}(page)

@allure.feature("自动化生成测试")
class TestAutoGenerated:
    @allure.story("正向测试流程")
    def test_success_flow(self, {class_name.lower()}):
        {class_name.lower()}\\
'''

    # 使用动态导入的po_class
    method_calls = []
    for method in dir(po_class):
        if method.startswith("input_"):
            method_calls.append(f".{method}('test_input')")
        elif method.startswith("click_"):
            method_calls.append(f".{method}()")

    test_code += "\n            ".join(method_calls) + f'''

    @allure.story("逆向测试流程")
    def test_failure_flow(self, {class_name.lower()}):
        with allure.step("执行非法操作"):
            {class_name.lower()}\\
'''

    failure_calls = []
    for method in dir(po_class):
        if method.startswith("input_"):
            failure_calls.append(f".{method}('invalid_input')")
        elif method.startswith("click_"):
            failure_calls.append(f".{method}()")

    # 确保 click_login_button 在 input 之后
    input_methods = [mc for mc in failure_calls if 'click_' not in mc]
    click_methods = [mc for mc in failure_calls if 'click_' in mc]
    failure_calls = input_methods + click_methods

    test_code += "\n            ".join(failure_calls) + f'''

        with allure.step("验证错误提示"):
            error_locator = {class_name.lower()}.page.locator("div.error-message")
            assert error_locator.is_visible(), "应该显示错误提示"
            allure.attach(
                {class_name.lower()}.page.screenshot(),
                name="错误提示截图",
                attachment_type=allure.attachment_type.PNG
            )
'''

    with open(f"test_{class_name.lower()}.py", "w", encoding='utf-8') as f:
        f.write(test_code)


if __name__ == "__main__":
    # 使用类名字符串而不是实例
    class_name = "LoginPage"
    generate_test_case(class_name)
