import re
from playwright.sync_api import Playwright, sync_playwright, expect


def run(playwright: Playwright) -> None:
    browser = playwright.chromium.launch(headless=False)
    context = browser.new_context()
    page = context.new_page()
    page.goto("http://paylabs-test.com/merchant/paylabs-register-register.html#")
    page.get_by_role("textbox", name="E-mail *", exact=True).click()
    page.get_by_role("textbox", name="E-mail *", exact=True).fill("paylabs2@test.com")
    page.get_by_role("textbox", name="Kode Verifikasi E-mail *").click()
    page.get_by_role("textbox", name="Kode Verifikasi E-mail *").click()
    page.get_by_role("textbox", name="Kode Verifikasi E-mail *").fill("652266")
    page.get_by_role("textbox", name="Masukkan nomor telepon Anda").click()
    page.get_by_role("textbox", name="Masukkan nomor telepon Anda").fill("15318544125")
    page.get_by_role("textbox", name="Masukkan kode verifikasi SMS").click()
    page.get_by_role("textbox", name="Masukkan kode verifikasi SMS").fill("652266")
    page.get_by_role("textbox", name="E-mail Payout *").click()
    page.get_by_role("textbox", name="E-mail Payout *").fill("paylabs2@test.com")
    page.get_by_role("textbox", name="Masukkan nama PIC Merchant").click()
    page.get_by_role("textbox", name="Masukkan nama PIC Merchant").fill("paylabs2@test.com")
    page.get_by_role("textbox", name="Password *").click()
    page.get_by_role("textbox", name="Password *").fill("Abc@123456789")
    page.get_by_role("textbox", name="Konfirmasi Password Anda *").click()
    page.get_by_role("textbox", name="Konfirmasi Password Anda *").fill("Abc@123456789")
    page.get_by_role("button", name="Daftar").click()
    page.get_by_role("button", name="Saya telah membaca dan").click()
    page.get_by_role("link", name="Masuk").click()
    page.get_by_role("textbox", name="E-mail").click()
    page.get_by_role("textbox", name="E-mail").fill("paylabs2@test.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Abc@123456789")
    page.locator("#mpanel2 i").click()
    page.get_by_role("button", name="Login").click()
    page.get_by_role("textbox", name="Google Verification Code").click()
    page.get_by_role("textbox", name="Google Verification Code").fill("125635")
    page.get_by_role("button", name="Bound").click()
    page.get_by_text("The Google verification code is incorrect, please reenter").click()
    page.get_by_role("button", name="Go to login").click()
    page.get_by_role("textbox", name="E-mail").click()
    page.get_by_role("textbox", name="E-mail").fill("")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="E-mail").click()
    page.get_by_role("textbox", name="E-mail").fill("paylabs2@test.com")
    page.get_by_role("textbox", name="Password").click()
    page.get_by_role("textbox", name="Password").fill("Abc@123456789")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("textbox", name="Google Verification Code").click()
    page.get_by_role("textbox", name="Google Verification Code").click()
    page.get_by_role("textbox", name="Google Verification Code").fill("382876")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("textbox", name="Google Verification Code").click()
    page.get_by_role("textbox", name="Google Verification Code").fill("649617")
    page.get_by_role("button", name="Login").click()
    page.get_by_role("heading", name="Payin Summary").click()
    page.get_by_role("link", name="Payout Summary").click()
    page.get_by_role("link", name="﮹ Accounts ").click()
    page.get_by_role("link", name="Accounts", exact=True).click()
    page.get_by_role("link", name="Settlement Record").click()
    page.get_by_role("link", name="VAT Monthly Report").click()
    page.get_by_role("link", name="Top-up Code Record").click()
    page.get_by_role("link", name="Transfer Record").click()
    page.get_by_role("link", name="Single Transfer").click()
    page.get_by_role("link", name="Batch Transfer").click()
    page.get_by_role("link", name="Withdraw").click()
    page.get_by_role("link", name="Transaction Data").click()
    page.get_by_role("link", name=" Tool ").click()
    page.get_by_role("link", name="Order Generator").click()
    page.get_by_role("link", name="Invoice Generator").click()
    page.get_by_role("link", name="Reconciliation File").click()
    page.get_by_role("link", name=" Settings ").click()
    page.get_by_role("link", name="My Store").click()
    page.get_by_role("link", name="Operator").click()
    page.get_by_role("link", name="Operation Log").click()
    page.get_by_role("link", name="Single Payout Limit").click()
    page.get_by_role("link", name="Freeze Payout").click()
    page.get_by_role("link", name="System Information").click()
    page.get_by_role("link", name="2FA").click()
    expect(page.locator("body")).to_contain_text("Google Verification Code Status")
    page.close()

    # ---------------------
    context.close()
    browser.close()


with sync_playwright() as playwright:
    run(playwright)
